version: 2
jobs:
  build:
    docker:
      - image: 'redislabsmodules/rmbuilder:latest'
    environment:
      - WORKSPACE: /tmp/workspace
    steps:
      - checkout
      - run:
          name: Build
          command: make -j 8
      - run:
          name: Test
          command: make test
      - run: mkdir -p $WORKSPACE/build
      - run: cp src/redisearch.so $WORKSPACE/
      - run: cp ramp.yml $WORKSPACE/
      - persist_to_workspace:
          root: $WORKSPACE
          paths:
            - redisearch.so
            - ramp.yml
            - build
  package_branch:
    docker:
      - image: 'redislabsmodules/rmbuilder:latest'
    environment:
      - WORKSPACE: /tmp/workspace
      - MODULE: redisearch-oss
    steps:
      - attach_workspace:
          at: $WORKSPACE
      - run:
          name: Package
          command: >-
            ramp-packer -m $WORKSPACE/ramp.yml -o
            $WORKSPACE/build/$MODULE.{os}-{architecture}.$CIRCLE_BRANCH.zip
            $WORKSPACE/redisearch.so
      - persist_to_workspace:
          root: $WORKSPACE
          paths:
            - build
  package_release:
    docker:
      - image: 'redislabsmodules/rmbuilder:latest'
    steps:
      - attach_workspace:
          at: $WORKSPACE
      - run:
          name: Package
          command: >-
            ramp-packer -m $WORKSPACE/ramp.yml -o
            $WORKSPACE/build/$MODULE.{os}-{architecture}.{semantic_version}.zip
            $WORKSPACE/redisearch.so
      - run:
          name: Package
          command: >-
            ramp-packer -m $WORKSPACE/ramp.yml -o
            $WORKSPACE/build/$MODULE.{os}-{architecture}.latest.zip
            $WORKSPACE/redisearch.so
      - persist_to_workspace:
          root: $WORKSPACE
          paths:
            - 'build'
      - store_artifacts:
          path: $WORKSPACE/build
  deploy_branch:
    docker:
      - image: 'redislabsmodules/rmbuilder:latest'
    environment:
      - WORKSPACE: /tmp/workspace
    working_directory: /tmp/my-project
    steps:
      - attach_workspace:
          at: $WORKSPACE
      - run:
          name: Deploy to S3
          command: >-
            aws s3 cp $WORKSPACE/build/ s3://redismodules/$MODULE/
            --recursive --exclude "*" --include "*.zip"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - package_branch:
          requires:
            - build
          filters:
            branches:
              only: circleci
      - package_release:
          requires:
            - build
          filters:
            tags:
              only: '/^v[0-9].*/'
      - deploy_branch:
          requires:
            - package_branch
