version: 2
jobs:
  build:
    docker:
      - image: redislabsmodules/rmbuilder:latest

    steps:
      - checkout
      - run:
          name: Build
          command: 'make -j 8'
      - run:
          name: Test
          command: make test
      # Copy the stuff needed for packaging to tmp workspace
      - run: mkdir -p /tmp/workspace
      - run: cp src/redisearch.so /tmp/workspace/
      - run: cp ramp.yml /tmp/workspace/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - redisearch.so
            - ramp.yml
  
  package_branch:
    docker:
      - image: redislabsmodules/rmbuilder:latest
    steps:
      
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Package
          command: ramp-packer -m /tmp/workspace/ramp.yml -o redisearch-oss.{os}-{architecture}.$CIRCLE_BRANCH.zip /tmp/workspace/redisearch.so
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - *.zip
  package_release:
    docker:
      - image: redislabsmodules/rmbuilder:latest
    steps:
      
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Package
          command: ramp-packer -m /tmp/workspace/ramp.yml -o redisearch-oss.{os}-{architecture}.{semantic_version}.zip /tmp/workspace/redisearch.so
      - run:
          name: Package
          command: ramp-packer -m /tmp/workspace/ramp.yml -o redisearch-oss.{os}-{architecture}.latest.zip /tmp/workspace/redisearch.so
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - *.zip
      - store_artifacts:
          path: ./*.zip
  deploy_branch:
    docker:
      - image: redislabsmodules/rmbuilder:latest
    working_directory: /tmp/my-project  
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy to S3
          command: aws s3 cp /tmp/workspace s3://redismodules/redisearch-oss/ --recursive --exclude "*" --include "*.zip"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - package_branch:
          requires:
            - build
          filters:
            branches:
              only: circleci
      - package_release:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9].*/
      - deploy_branch:
          requires:
            - package_branch
